### ISSUE TITLE
`pacdef unmanaged` reports duplicated packages for the three arch based backends

### ISSUE THREAD

**Issue by ripytide** [ripytide/pacdef#16]
Perhaps we could add a config option for selecting which of the three backends to use for querying installed arch packages? This would then still allow users to select different backends when installing arch packages.

**Comment by ripytide** [comment]
The same issue will apply for removing arch based packages, maybe we should just use `pacman` for querying/removing packages and then allow installing packages from any of the three package managers?

**Comment by InnocentZero** [comment]
The problem with using just pacman is that paru and yay and other aur helpers are able to query the installed AUR packages as well. I'm not sure if pacman does.
EDIT: Just checked, it doesn't.

**Comment by InnocentZero** [comment]
This issue isn't restricted to pacman though. I can totally expect Ubuntu 24.04 to have the same issue with pip and apt as well. pip is another issue that we need to take care of.

**Comment by InnocentZero** [comment]
I suggest we add a `new(config: &Config)` function to the backend that allows us to configure the backend as per the config. That also allows us to basically _deregister_ a backend in case it's in the ignore_backends list.

**Comment by ripytide** [comment]
I think pacman does show locally installed aur packages since you can uninstall them using pacman. Does pip clash with apt packages too? Instead of adding `new(config, &Config)` could we not use the `&Config` already passed to each of the `Backend` trait methods, although for a possible `disabled_backends` settings that might be easier to implement in the `all.rs` file.

**Comment by InnocentZero** [comment]
My bad, pacman does query AUR packages. Anyways, yes I've seen pip clash with apt on Ubuntu 24.04. The reason I suggested a `new()` function was so that a lot of boilerplate code in the remaining backend trait functions (such as checking for something every single time) can be abstracted away. That function could return an Option and we could match against it.
