### ISSUE TITLE
Duplication of packages

### ISSUE THREAD

**Issue by InnocentZero** [ripytide/pacdef#21]
I'm seeing a lot of duplication of packages everywhere. I'm not sure why this is the case, but believe me when I say this, I doubt anyone using arch would be using more than one AUR helper. In any case, I not having yay installed on my system should imply that yay is unmanaged. Why is that not the case? Similarly, paru and pacman report the same packages. This is problematic.

**Comment by InnocentZero** [comment]
I suggest we go back to having the AUR helper as a string in the config file and using that value with a default of pacman. That would reduce redundant files and simplify work quite a bit.

**Comment by ripytide** [comment]
See #16

**Comment by ripytide** [comment]
I agree though, I didn't foresee this issue and thought having multiple backends would be a cleaner solution. Going back to a global config seems like the best solution now 👍
