### ISSUE TITLE
Add pikaur

### ISSUE THREAD

**Issue by keilmillerjr** [ripytide/pacdef#35]
I would like to add [pikaur](https://github.com/actionless/pikaur) as an arch backend in a PR.

**Comment by ripytide** [comment]
Go for it :+1:

**Comment by ripytide** [comment]
I'm assuming you read the `CONTRIBUTING.md` which I think was still the same as from `pacdef`, I've re-written it to how I like to run projects now such that you might not have needed to get approval before opening a PR but of course there was no harm in asking.
