### ISSUE TITLE
Add `metapac group` command

### ISSUE THREAD

**Issue by watzon** [ripytide/pacdef#55]
It would be nice if you could manage groups from the CLI. So far I'm imagining `init`, `remove`, `list` and `edit` subcommands which I think are all pretty self explanatory. It would just be a small quality of life improvement over having to manually create, delete, list, and edit the files in the `~/.config/metapac/groups` directory.

**Comment by ripytide** [comment]
To the contrary, it goes against the unix philosophy, rather users could learn to use standard tools for such functionality which don't have to be re-learnt for every tool they want to interact with. `cat`, `vim`, `ls`, `ln`, `mkdir`, `rm` etc..

**Comment by watzon** [comment]
That's fair enough I suppose
